// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"google.golang.org/grpc"
	"helloworld/internal/biz"
	"helloworld/internal/data"
	"helloworld/internal/server"
	"helloworld/internal/service"
)

// Injectors from wire.go:

func InitSvr() *grpc.Server {
	helloRepo := data.NewHelloRepo()
	helloUsecase := biz.NewHelloUsecase(helloRepo)
	helloService := service.NewHelloService(helloUsecase)
	grpcServer := server.NewGRPCServer(helloService)
	return grpcServer
}
